### ISSUE TITLE
Type checking + `slice(-1)`

### ISSUE THREAD

**Issue by ruffle1986** [IonicaBizau/last-char#1]
Hi,

I'd like to use your module in production code but first it has to fit some prerequisites.

A. I think the function should check whether it really gets a string as a first parameter, otherwise it should throw a `TypeError`.
B. Imho using `.slice(-1)` would be more elegant than the current implementation.

After closing this issue, I'd like to write a few tests for this project.

Thank you.

**Comment by IonicaBizau** [comment]
Hey @ruffle1986! :star: 

That's awesome! I commented on your PR. :grin:
