### ISSUE TITLE
add tests

### ISSUE THREAD

**Issue by ruffle1986** [IonicaBizau/last-char#3]
I usually use [tape](https://www.npmjs.com/package/tape). Thoughts on this?

**Comment by IonicaBizau** [comment]
I use `mocha`. [Here](https://github.com/IonicaBizau/node-oargv/blob/11f652e3800f0c2166b5e7202ecdf68bd861315c/test/index.js) is an example.

**Comment by ruffle1986** [comment]
assume you prefer `mocha` but you should take a look at tape because it's so easy to use and it has zero configuration process to start to work with it. But as you wish of course.

**Comment by IonicaBizau** [comment]
@ruffle1986 I did use `tape` in the past, but switched to `mocha`. It's on my list to create a minimal testing module, lol. :grinning:

**Comment by ruffle1986** [comment]
really? can I ask why? I'm just curious.

**Comment by IonicaBizau** [comment]
I just didn't feel comfortable with it. Also, `mocha` is not my favorite, but it's the best I found yet... :smile:

**Comment by ruffle1986** [comment]
I see. :+1: let's use mocha.

**Comment by IonicaBizau** [comment]
Btw, I'm happy to see Hungarian neighborhoods around! Greetings from Bihor, Romania! :smile:

**Comment by ruffle1986** [comment]
Cheers! :wine_glass: Be well Neighbour! :D

**Comment by ruffle1986** [comment]
Which assertion library do you prefer? I use `should`.

**Comment by IonicaBizau** [comment]
@ruffle1986 Just `require("assert")`. If I'm not wrong, it's built-int. :smile:

**Comment by ruffle1986** [comment]
:+1:

**Comment by IonicaBizau** [comment]
This was fixed via #4 already :sparkles: 

@ruffle1986 Just an update: I published [`tester`](https://github.com/IonicaBizau/tester) which is the unit testing library I will use in the future (in most of the cases).

**Comment by ruffle1986** [comment]
@IonicaBizau Great! I'll take a look.
